### ISSUE TITLE
Design Revision for Header in Mobile View

### ISSUE THREAD

**Issue by OmurCataltepe** [friedger/stacks-send-many#12]
![image](https://user-images.githubusercontent.com/33328414/118675158-0b5d2b00-b803-11eb-8312-19be2d0c46e3.png)

- [ ] Design Revision

**Comment by friedger** [comment]
New design
![Screenshot from 2021-07-12 23-09-06](https://user-images.githubusercontent.com/1449049/125356210-3036d000-e366-11eb-8760-dbf55a358311.png)
