### ISSUE TITLE
Testnet contract address incorrect

### ISSUE THREAD

**Issue by whoabuddy** [friedger/stacks-send-many#27]
I was trying to send-many on testnet and ran into this error from the wallet:

`Your transaction failed to broadcast because of the error: contract does not exist - transaction rejected`

Looking at the pop-up window it's trying to call `STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C.send-many`.

Looking at the explorer, this [contract does not exist](https://explorer.stacks.co/txid/STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C.send-many?chain=testnet) and there are [no transactions for the address](https://explorer.stacks.co/address/STR8P3RD1EHA8AA37ERSSSZSWKS9T2GYQFGXNA4C?chain=testnet).

If I can find the send-many contract on testnet I'll post a link here.

**Comment by friedger** [comment]
It has been deployes as https://explorer.hiro.so/txid/ST3FFRX7C911PZP5RHE148YDVDD9JWVS6FZRA60VS.send-many?chain=testnet
