### ISSUE TITLE
URL params recipient, amount, token

### ISSUE THREAD

**Issue by hozzjss** [friedger/stacks-send-many#31]
I was thinking of having a url format for sending amounts to a list of recipients with amounts. 
The benefit of that being we could use sendstx as a general service for transferring tokens for the whole community.
For consumers they could use a helper function to generate a compliant URL an example implementation that can construct the url for send many including the token name and a list of recipients like
```ts
const params = new URLSearchParams([
  ["recipient", 'SP1...MZ,1000,"thanks"'],
  ['recipient', 'hz.btc,1000,"shokran"'],
  ['recipient', 'friedger.btc,1000,"danke"'],
])

const sendSTXURL = `https://sendstx.com/not?${params.toString()}`
```
You might ask why is that and my purpose from this is to have a trusted place where people can send tokens that might help me in my personal project delegate trust of deposits to sendstx I want to support contract addresses in the future as well.

We could even go further with this by providing support for arbitrary tokens like `sendstx.com/sp...kkz.nope?params` and the app can fetch the abi of the contract to check that there is a compatible send-many function and if so use that and secure it with post conditions, decimals as well can be retrieved by using the `get-decimals` function.

**Comment by friedger** [comment]
Are there other chains that offer a similar service? With similar parameters?

**Comment by hozzjss** [comment]
Not to my knowledge, what would you propose, I know a CSV file exists and paste as well but what about just a payment link is what I'm thinking something like a central place where people can send their tokens
