### ISSUE TITLE
Add new tokens on sendstx

### ISSUE THREAD

**Issue by xyzerobtc** [friedger/stacks-send-many#45]
hello friend
https://sendstx.com/
i was talking to Haz and i wanted to ask you if you can add tokens:

SP2C1WREHGM75C7TGFAEJPFKTFTEGZKF6DFT6E2GE.kangaroo
SP1AY6K3PQV5MRT6R4S671NWW2FRVPKM0BR162CT6.leo-token
SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token
SP3NE50GEXFG9SZGTT51P40X2CKYSZ5CC4ZTZ7A2G.welshcorgicoin-token
SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.mega
SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.usda-token
SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.ststx-token
SP3Y2ZSH8P7D50B0VBTSX11S7XSG24M1VB9YFQA4K.token-aeusdc

**Comment by friedger** [comment]
There are two ROO tokens. Which is the correct one?

![image](https://github.com/user-attachments/assets/cc6fc117-7b4a-40bc-8538-42039eee29a2)

**Comment by xyzerobtc** [comment]
https://explorer.hiro.so/txid/SP2C1WREHGM75C7TGFAEJPFKTFTEGZKF6DFT6E2GE.kangaroo?chain=mainnet

**Comment by xyzerobtc** [comment]
Are you on twitter anymore?

**Comment by xyzerobtc** [comment]
Can you please add VELAR. 

https://explorer.hiro.so/txid/SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.velar-token?chain=mainnet

**Comment by friedger** [comment]
All added
![image](https://github.com/user-attachments/assets/72bb71a2-77b6-467b-ae54-f7eb24ec87fd)
